import mysql.connector
mydb = mysql.connector.connect(host="localhost", user="root", passwd="",database='inventory')
db = mydb.cursor()
db.execute("use inventory")
db.execute("Insert into inventory values('1','pen',669,'y',10);")
db.execute("Insert into inventory values('2','tissue',115,'y',100);")
db.execute("Insert into inventory values('3','soap',69,'y',65);")
db.execute("Insert into inventory values('4','shampo',200,'y',75);")
db.execute("Insert into inventory values('5','battery',0,'n',30);")
db.execute("Insert into inventory values('6','knife',0,'n',200);")
db.execute("Insert into inventory values('7','LED light',339,'y',100);")
db.execute("Insert into inventory values('8','chocolate',700,'y',35);")
db.execute("Insert into inventory values('9','printer',50,'y',7700);")
db.execute("Insert into inventory values('10','printer ink',50,'y',193 );")
db.execute("Insert into inventory values('11','clear file',78,'y',50);")
db.execute("Insert into inventory values('12','color pencil',56,'y',45);")
db.execute("Insert into inventory values('13','color paint',90,'y',75);")
db.execute("Insert into inventory values('14','water bottle',0,'n',100);")
db.execute("Insert into inventory values('15','notebook',408,'y',45);")
db.execute("Insert into inventory values('16','toothpaste',57,'y',60);")
db.execute("Insert into inventory values('17','toothbrushes',0,'n',40);")
db.execute("Insert into inventory values('18','whitener',123,'y',35);")
db.execute("Insert into inventory values('19','scale',43,'y',25);")
db.execute("Insert into inventory values('20','magnifying glass',0,'n',55);")
mydb.commit()